name: Gemeindescan-Package-Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build
      run: |
        python package-builder.py
    - uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_message: Auto Commit
        branch: ${{ github.head_ref }}
